// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_hello_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_hello_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_hello_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_hello_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_hello_2eproto;
namespace aafs {
class FileContent;
struct FileContentDefaultTypeInternal;
extern FileContentDefaultTypeInternal _FileContent_default_instance_;
class GetAttrResponse;
struct GetAttrResponseDefaultTypeInternal;
extern GetAttrResponseDefaultTypeInternal _GetAttrResponse_default_instance_;
class PathRequest;
struct PathRequestDefaultTypeInternal;
extern PathRequestDefaultTypeInternal _PathRequest_default_instance_;
class ReadDirResponse;
struct ReadDirResponseDefaultTypeInternal;
extern ReadDirResponseDefaultTypeInternal _ReadDirResponse_default_instance_;
class Stat;
struct StatDefaultTypeInternal;
extern StatDefaultTypeInternal _Stat_default_instance_;
}  // namespace aafs
PROTOBUF_NAMESPACE_OPEN
template<> ::aafs::FileContent* Arena::CreateMaybeMessage<::aafs::FileContent>(Arena*);
template<> ::aafs::GetAttrResponse* Arena::CreateMaybeMessage<::aafs::GetAttrResponse>(Arena*);
template<> ::aafs::PathRequest* Arena::CreateMaybeMessage<::aafs::PathRequest>(Arena*);
template<> ::aafs::ReadDirResponse* Arena::CreateMaybeMessage<::aafs::ReadDirResponse>(Arena*);
template<> ::aafs::Stat* Arena::CreateMaybeMessage<::aafs::Stat>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace aafs {

// ===================================================================

class Stat final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aafs.Stat) */ {
 public:
  inline Stat() : Stat(nullptr) {}
  ~Stat() override;
  explicit constexpr Stat(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Stat(const Stat& from);
  Stat(Stat&& from) noexcept
    : Stat() {
    *this = ::std::move(from);
  }

  inline Stat& operator=(const Stat& from) {
    CopyFrom(from);
    return *this;
  }
  inline Stat& operator=(Stat&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Stat& default_instance() {
    return *internal_default_instance();
  }
  static inline const Stat* internal_default_instance() {
    return reinterpret_cast<const Stat*>(
               &_Stat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Stat& a, Stat& b) {
    a.Swap(&b);
  }
  inline void Swap(Stat* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Stat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Stat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Stat>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Stat& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Stat& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Stat* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aafs.Stat";
  }
  protected:
  explicit Stat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInoFieldNumber = 1,
    kModeFieldNumber = 2,
    kNlinkFieldNumber = 3,
    kUidFieldNumber = 4,
    kGidFieldNumber = 5,
    kRdevFieldNumber = 6,
    kSizeFieldNumber = 7,
    kBlocksFieldNumber = 8,
    kAtimeFieldNumber = 9,
    kMtimeFieldNumber = 10,
    kCtimeFieldNumber = 11,
  };
  // uint64 ino = 1;
  void clear_ino();
  uint64_t ino() const;
  void set_ino(uint64_t value);
  private:
  uint64_t _internal_ino() const;
  void _internal_set_ino(uint64_t value);
  public:

  // uint64 mode = 2;
  void clear_mode();
  uint64_t mode() const;
  void set_mode(uint64_t value);
  private:
  uint64_t _internal_mode() const;
  void _internal_set_mode(uint64_t value);
  public:

  // uint64 nlink = 3;
  void clear_nlink();
  uint64_t nlink() const;
  void set_nlink(uint64_t value);
  private:
  uint64_t _internal_nlink() const;
  void _internal_set_nlink(uint64_t value);
  public:

  // uint64 uid = 4;
  void clear_uid();
  uint64_t uid() const;
  void set_uid(uint64_t value);
  private:
  uint64_t _internal_uid() const;
  void _internal_set_uid(uint64_t value);
  public:

  // uint64 gid = 5;
  void clear_gid();
  uint64_t gid() const;
  void set_gid(uint64_t value);
  private:
  uint64_t _internal_gid() const;
  void _internal_set_gid(uint64_t value);
  public:

  // uint64 rdev = 6;
  void clear_rdev();
  uint64_t rdev() const;
  void set_rdev(uint64_t value);
  private:
  uint64_t _internal_rdev() const;
  void _internal_set_rdev(uint64_t value);
  public:

  // int64 size = 7;
  void clear_size();
  int64_t size() const;
  void set_size(int64_t value);
  private:
  int64_t _internal_size() const;
  void _internal_set_size(int64_t value);
  public:

  // int64 blocks = 8;
  void clear_blocks();
  int64_t blocks() const;
  void set_blocks(int64_t value);
  private:
  int64_t _internal_blocks() const;
  void _internal_set_blocks(int64_t value);
  public:

  // int64 atime = 9;
  void clear_atime();
  int64_t atime() const;
  void set_atime(int64_t value);
  private:
  int64_t _internal_atime() const;
  void _internal_set_atime(int64_t value);
  public:

  // int64 mtime = 10;
  void clear_mtime();
  int64_t mtime() const;
  void set_mtime(int64_t value);
  private:
  int64_t _internal_mtime() const;
  void _internal_set_mtime(int64_t value);
  public:

  // int64 ctime = 11;
  void clear_ctime();
  int64_t ctime() const;
  void set_ctime(int64_t value);
  private:
  int64_t _internal_ctime() const;
  void _internal_set_ctime(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:aafs.Stat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  uint64_t ino_;
  uint64_t mode_;
  uint64_t nlink_;
  uint64_t uid_;
  uint64_t gid_;
  uint64_t rdev_;
  int64_t size_;
  int64_t blocks_;
  int64_t atime_;
  int64_t mtime_;
  int64_t ctime_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hello_2eproto;
};
// -------------------------------------------------------------------

class PathRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aafs.PathRequest) */ {
 public:
  inline PathRequest() : PathRequest(nullptr) {}
  ~PathRequest() override;
  explicit constexpr PathRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  PathRequest(const PathRequest& from);
  PathRequest(PathRequest&& from) noexcept
    : PathRequest() {
    *this = ::std::move(from);
  }

  inline PathRequest& operator=(const PathRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PathRequest& operator=(PathRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PathRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const PathRequest* internal_default_instance() {
    return reinterpret_cast<const PathRequest*>(
               &_PathRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PathRequest& a, PathRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PathRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PathRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PathRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PathRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const PathRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const PathRequest& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PathRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aafs.PathRequest";
  }
  protected:
  explicit PathRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kPathFieldNumber = 1,
  };
  // string path = 1;
  void clear_path();
  const std::string& path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_path();
  PROTOBUF_NODISCARD std::string* release_path();
  void set_allocated_path(std::string* path);
  private:
  const std::string& _internal_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_path(const std::string& value);
  std::string* _internal_mutable_path();
  public:

  // @@protoc_insertion_point(class_scope:aafs.PathRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr path_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hello_2eproto;
};
// -------------------------------------------------------------------

class GetAttrResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aafs.GetAttrResponse) */ {
 public:
  inline GetAttrResponse() : GetAttrResponse(nullptr) {}
  ~GetAttrResponse() override;
  explicit constexpr GetAttrResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  GetAttrResponse(const GetAttrResponse& from);
  GetAttrResponse(GetAttrResponse&& from) noexcept
    : GetAttrResponse() {
    *this = ::std::move(from);
  }

  inline GetAttrResponse& operator=(const GetAttrResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline GetAttrResponse& operator=(GetAttrResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GetAttrResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const GetAttrResponse* internal_default_instance() {
    return reinterpret_cast<const GetAttrResponse*>(
               &_GetAttrResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(GetAttrResponse& a, GetAttrResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(GetAttrResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GetAttrResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GetAttrResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<GetAttrResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const GetAttrResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const GetAttrResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GetAttrResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aafs.GetAttrResponse";
  }
  protected:
  explicit GetAttrResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatFieldNumber = 2,
    kRetFieldNumber = 1,
  };
  // .aafs.Stat stat = 2;
  bool has_stat() const;
  private:
  bool _internal_has_stat() const;
  public:
  void clear_stat();
  const ::aafs::Stat& stat() const;
  PROTOBUF_NODISCARD ::aafs::Stat* release_stat();
  ::aafs::Stat* mutable_stat();
  void set_allocated_stat(::aafs::Stat* stat);
  private:
  const ::aafs::Stat& _internal_stat() const;
  ::aafs::Stat* _internal_mutable_stat();
  public:
  void unsafe_arena_set_allocated_stat(
      ::aafs::Stat* stat);
  ::aafs::Stat* unsafe_arena_release_stat();

  // int32 ret = 1;
  void clear_ret();
  int32_t ret() const;
  void set_ret(int32_t value);
  private:
  int32_t _internal_ret() const;
  void _internal_set_ret(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:aafs.GetAttrResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::aafs::Stat* stat_;
  int32_t ret_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hello_2eproto;
};
// -------------------------------------------------------------------

class ReadDirResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aafs.ReadDirResponse) */ {
 public:
  inline ReadDirResponse() : ReadDirResponse(nullptr) {}
  ~ReadDirResponse() override;
  explicit constexpr ReadDirResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ReadDirResponse(const ReadDirResponse& from);
  ReadDirResponse(ReadDirResponse&& from) noexcept
    : ReadDirResponse() {
    *this = ::std::move(from);
  }

  inline ReadDirResponse& operator=(const ReadDirResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReadDirResponse& operator=(ReadDirResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReadDirResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReadDirResponse* internal_default_instance() {
    return reinterpret_cast<const ReadDirResponse*>(
               &_ReadDirResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ReadDirResponse& a, ReadDirResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(ReadDirResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReadDirResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReadDirResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReadDirResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ReadDirResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const ReadDirResponse& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReadDirResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aafs.ReadDirResponse";
  }
  protected:
  explicit ReadDirResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEntriesFieldNumber = 2,
    kRetFieldNumber = 1,
  };
  // repeated string entries = 2;
  int entries_size() const;
  private:
  int _internal_entries_size() const;
  public:
  void clear_entries();
  const std::string& entries(int index) const;
  std::string* mutable_entries(int index);
  void set_entries(int index, const std::string& value);
  void set_entries(int index, std::string&& value);
  void set_entries(int index, const char* value);
  void set_entries(int index, const char* value, size_t size);
  std::string* add_entries();
  void add_entries(const std::string& value);
  void add_entries(std::string&& value);
  void add_entries(const char* value);
  void add_entries(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& entries() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_entries();
  private:
  const std::string& _internal_entries(int index) const;
  std::string* _internal_add_entries();
  public:

  // int32 ret = 1;
  void clear_ret();
  int32_t ret() const;
  void set_ret(int32_t value);
  private:
  int32_t _internal_ret() const;
  void _internal_set_ret(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:aafs.ReadDirResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> entries_;
  int32_t ret_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hello_2eproto;
};
// -------------------------------------------------------------------

class FileContent final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aafs.FileContent) */ {
 public:
  inline FileContent() : FileContent(nullptr) {}
  ~FileContent() override;
  explicit constexpr FileContent(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileContent(const FileContent& from);
  FileContent(FileContent&& from) noexcept
    : FileContent() {
    *this = ::std::move(from);
  }

  inline FileContent& operator=(const FileContent& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileContent& operator=(FileContent&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileContent& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileContent* internal_default_instance() {
    return reinterpret_cast<const FileContent*>(
               &_FileContent_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(FileContent& a, FileContent& b) {
    a.Swap(&b);
  }
  inline void Swap(FileContent* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileContent* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileContent* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileContent>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const FileContent& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const FileContent& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileContent* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aafs.FileContent";
  }
  protected:
  explicit FileContent(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
  };
  // bytes data = 1;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // @@protoc_insertion_point(class_scope:aafs.FileContent)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hello_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Stat

// uint64 ino = 1;
inline void Stat::clear_ino() {
  ino_ = uint64_t{0u};
}
inline uint64_t Stat::_internal_ino() const {
  return ino_;
}
inline uint64_t Stat::ino() const {
  // @@protoc_insertion_point(field_get:aafs.Stat.ino)
  return _internal_ino();
}
inline void Stat::_internal_set_ino(uint64_t value) {
  
  ino_ = value;
}
inline void Stat::set_ino(uint64_t value) {
  _internal_set_ino(value);
  // @@protoc_insertion_point(field_set:aafs.Stat.ino)
}

// uint64 mode = 2;
inline void Stat::clear_mode() {
  mode_ = uint64_t{0u};
}
inline uint64_t Stat::_internal_mode() const {
  return mode_;
}
inline uint64_t Stat::mode() const {
  // @@protoc_insertion_point(field_get:aafs.Stat.mode)
  return _internal_mode();
}
inline void Stat::_internal_set_mode(uint64_t value) {
  
  mode_ = value;
}
inline void Stat::set_mode(uint64_t value) {
  _internal_set_mode(value);
  // @@protoc_insertion_point(field_set:aafs.Stat.mode)
}

// uint64 nlink = 3;
inline void Stat::clear_nlink() {
  nlink_ = uint64_t{0u};
}
inline uint64_t Stat::_internal_nlink() const {
  return nlink_;
}
inline uint64_t Stat::nlink() const {
  // @@protoc_insertion_point(field_get:aafs.Stat.nlink)
  return _internal_nlink();
}
inline void Stat::_internal_set_nlink(uint64_t value) {
  
  nlink_ = value;
}
inline void Stat::set_nlink(uint64_t value) {
  _internal_set_nlink(value);
  // @@protoc_insertion_point(field_set:aafs.Stat.nlink)
}

// uint64 uid = 4;
inline void Stat::clear_uid() {
  uid_ = uint64_t{0u};
}
inline uint64_t Stat::_internal_uid() const {
  return uid_;
}
inline uint64_t Stat::uid() const {
  // @@protoc_insertion_point(field_get:aafs.Stat.uid)
  return _internal_uid();
}
inline void Stat::_internal_set_uid(uint64_t value) {
  
  uid_ = value;
}
inline void Stat::set_uid(uint64_t value) {
  _internal_set_uid(value);
  // @@protoc_insertion_point(field_set:aafs.Stat.uid)
}

// uint64 gid = 5;
inline void Stat::clear_gid() {
  gid_ = uint64_t{0u};
}
inline uint64_t Stat::_internal_gid() const {
  return gid_;
}
inline uint64_t Stat::gid() const {
  // @@protoc_insertion_point(field_get:aafs.Stat.gid)
  return _internal_gid();
}
inline void Stat::_internal_set_gid(uint64_t value) {
  
  gid_ = value;
}
inline void Stat::set_gid(uint64_t value) {
  _internal_set_gid(value);
  // @@protoc_insertion_point(field_set:aafs.Stat.gid)
}

// uint64 rdev = 6;
inline void Stat::clear_rdev() {
  rdev_ = uint64_t{0u};
}
inline uint64_t Stat::_internal_rdev() const {
  return rdev_;
}
inline uint64_t Stat::rdev() const {
  // @@protoc_insertion_point(field_get:aafs.Stat.rdev)
  return _internal_rdev();
}
inline void Stat::_internal_set_rdev(uint64_t value) {
  
  rdev_ = value;
}
inline void Stat::set_rdev(uint64_t value) {
  _internal_set_rdev(value);
  // @@protoc_insertion_point(field_set:aafs.Stat.rdev)
}

// int64 size = 7;
inline void Stat::clear_size() {
  size_ = int64_t{0};
}
inline int64_t Stat::_internal_size() const {
  return size_;
}
inline int64_t Stat::size() const {
  // @@protoc_insertion_point(field_get:aafs.Stat.size)
  return _internal_size();
}
inline void Stat::_internal_set_size(int64_t value) {
  
  size_ = value;
}
inline void Stat::set_size(int64_t value) {
  _internal_set_size(value);
  // @@protoc_insertion_point(field_set:aafs.Stat.size)
}

// int64 blocks = 8;
inline void Stat::clear_blocks() {
  blocks_ = int64_t{0};
}
inline int64_t Stat::_internal_blocks() const {
  return blocks_;
}
inline int64_t Stat::blocks() const {
  // @@protoc_insertion_point(field_get:aafs.Stat.blocks)
  return _internal_blocks();
}
inline void Stat::_internal_set_blocks(int64_t value) {
  
  blocks_ = value;
}
inline void Stat::set_blocks(int64_t value) {
  _internal_set_blocks(value);
  // @@protoc_insertion_point(field_set:aafs.Stat.blocks)
}

// int64 atime = 9;
inline void Stat::clear_atime() {
  atime_ = int64_t{0};
}
inline int64_t Stat::_internal_atime() const {
  return atime_;
}
inline int64_t Stat::atime() const {
  // @@protoc_insertion_point(field_get:aafs.Stat.atime)
  return _internal_atime();
}
inline void Stat::_internal_set_atime(int64_t value) {
  
  atime_ = value;
}
inline void Stat::set_atime(int64_t value) {
  _internal_set_atime(value);
  // @@protoc_insertion_point(field_set:aafs.Stat.atime)
}

// int64 mtime = 10;
inline void Stat::clear_mtime() {
  mtime_ = int64_t{0};
}
inline int64_t Stat::_internal_mtime() const {
  return mtime_;
}
inline int64_t Stat::mtime() const {
  // @@protoc_insertion_point(field_get:aafs.Stat.mtime)
  return _internal_mtime();
}
inline void Stat::_internal_set_mtime(int64_t value) {
  
  mtime_ = value;
}
inline void Stat::set_mtime(int64_t value) {
  _internal_set_mtime(value);
  // @@protoc_insertion_point(field_set:aafs.Stat.mtime)
}

// int64 ctime = 11;
inline void Stat::clear_ctime() {
  ctime_ = int64_t{0};
}
inline int64_t Stat::_internal_ctime() const {
  return ctime_;
}
inline int64_t Stat::ctime() const {
  // @@protoc_insertion_point(field_get:aafs.Stat.ctime)
  return _internal_ctime();
}
inline void Stat::_internal_set_ctime(int64_t value) {
  
  ctime_ = value;
}
inline void Stat::set_ctime(int64_t value) {
  _internal_set_ctime(value);
  // @@protoc_insertion_point(field_set:aafs.Stat.ctime)
}

// -------------------------------------------------------------------

// PathRequest

// string path = 1;
inline void PathRequest::clear_path() {
  path_.ClearToEmpty();
}
inline const std::string& PathRequest::path() const {
  // @@protoc_insertion_point(field_get:aafs.PathRequest.path)
  return _internal_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void PathRequest::set_path(ArgT0&& arg0, ArgT... args) {
 
 path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aafs.PathRequest.path)
}
inline std::string* PathRequest::mutable_path() {
  std::string* _s = _internal_mutable_path();
  // @@protoc_insertion_point(field_mutable:aafs.PathRequest.path)
  return _s;
}
inline const std::string& PathRequest::_internal_path() const {
  return path_.Get();
}
inline void PathRequest::_internal_set_path(const std::string& value) {
  
  path_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* PathRequest::_internal_mutable_path() {
  
  return path_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* PathRequest::release_path() {
  // @@protoc_insertion_point(field_release:aafs.PathRequest.path)
  return path_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void PathRequest::set_allocated_path(std::string* path) {
  if (path != nullptr) {
    
  } else {
    
  }
  path_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), path,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (path_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    path_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:aafs.PathRequest.path)
}

// -------------------------------------------------------------------

// GetAttrResponse

// int32 ret = 1;
inline void GetAttrResponse::clear_ret() {
  ret_ = 0;
}
inline int32_t GetAttrResponse::_internal_ret() const {
  return ret_;
}
inline int32_t GetAttrResponse::ret() const {
  // @@protoc_insertion_point(field_get:aafs.GetAttrResponse.ret)
  return _internal_ret();
}
inline void GetAttrResponse::_internal_set_ret(int32_t value) {
  
  ret_ = value;
}
inline void GetAttrResponse::set_ret(int32_t value) {
  _internal_set_ret(value);
  // @@protoc_insertion_point(field_set:aafs.GetAttrResponse.ret)
}

// .aafs.Stat stat = 2;
inline bool GetAttrResponse::_internal_has_stat() const {
  return this != internal_default_instance() && stat_ != nullptr;
}
inline bool GetAttrResponse::has_stat() const {
  return _internal_has_stat();
}
inline void GetAttrResponse::clear_stat() {
  if (GetArenaForAllocation() == nullptr && stat_ != nullptr) {
    delete stat_;
  }
  stat_ = nullptr;
}
inline const ::aafs::Stat& GetAttrResponse::_internal_stat() const {
  const ::aafs::Stat* p = stat_;
  return p != nullptr ? *p : reinterpret_cast<const ::aafs::Stat&>(
      ::aafs::_Stat_default_instance_);
}
inline const ::aafs::Stat& GetAttrResponse::stat() const {
  // @@protoc_insertion_point(field_get:aafs.GetAttrResponse.stat)
  return _internal_stat();
}
inline void GetAttrResponse::unsafe_arena_set_allocated_stat(
    ::aafs::Stat* stat) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(stat_);
  }
  stat_ = stat;
  if (stat) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aafs.GetAttrResponse.stat)
}
inline ::aafs::Stat* GetAttrResponse::release_stat() {
  
  ::aafs::Stat* temp = stat_;
  stat_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::aafs::Stat* GetAttrResponse::unsafe_arena_release_stat() {
  // @@protoc_insertion_point(field_release:aafs.GetAttrResponse.stat)
  
  ::aafs::Stat* temp = stat_;
  stat_ = nullptr;
  return temp;
}
inline ::aafs::Stat* GetAttrResponse::_internal_mutable_stat() {
  
  if (stat_ == nullptr) {
    auto* p = CreateMaybeMessage<::aafs::Stat>(GetArenaForAllocation());
    stat_ = p;
  }
  return stat_;
}
inline ::aafs::Stat* GetAttrResponse::mutable_stat() {
  ::aafs::Stat* _msg = _internal_mutable_stat();
  // @@protoc_insertion_point(field_mutable:aafs.GetAttrResponse.stat)
  return _msg;
}
inline void GetAttrResponse::set_allocated_stat(::aafs::Stat* stat) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete stat_;
  }
  if (stat) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::aafs::Stat>::GetOwningArena(stat);
    if (message_arena != submessage_arena) {
      stat = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, stat, submessage_arena);
    }
    
  } else {
    
  }
  stat_ = stat;
  // @@protoc_insertion_point(field_set_allocated:aafs.GetAttrResponse.stat)
}

// -------------------------------------------------------------------

// ReadDirResponse

// int32 ret = 1;
inline void ReadDirResponse::clear_ret() {
  ret_ = 0;
}
inline int32_t ReadDirResponse::_internal_ret() const {
  return ret_;
}
inline int32_t ReadDirResponse::ret() const {
  // @@protoc_insertion_point(field_get:aafs.ReadDirResponse.ret)
  return _internal_ret();
}
inline void ReadDirResponse::_internal_set_ret(int32_t value) {
  
  ret_ = value;
}
inline void ReadDirResponse::set_ret(int32_t value) {
  _internal_set_ret(value);
  // @@protoc_insertion_point(field_set:aafs.ReadDirResponse.ret)
}

// repeated string entries = 2;
inline int ReadDirResponse::_internal_entries_size() const {
  return entries_.size();
}
inline int ReadDirResponse::entries_size() const {
  return _internal_entries_size();
}
inline void ReadDirResponse::clear_entries() {
  entries_.Clear();
}
inline std::string* ReadDirResponse::add_entries() {
  std::string* _s = _internal_add_entries();
  // @@protoc_insertion_point(field_add_mutable:aafs.ReadDirResponse.entries)
  return _s;
}
inline const std::string& ReadDirResponse::_internal_entries(int index) const {
  return entries_.Get(index);
}
inline const std::string& ReadDirResponse::entries(int index) const {
  // @@protoc_insertion_point(field_get:aafs.ReadDirResponse.entries)
  return _internal_entries(index);
}
inline std::string* ReadDirResponse::mutable_entries(int index) {
  // @@protoc_insertion_point(field_mutable:aafs.ReadDirResponse.entries)
  return entries_.Mutable(index);
}
inline void ReadDirResponse::set_entries(int index, const std::string& value) {
  entries_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:aafs.ReadDirResponse.entries)
}
inline void ReadDirResponse::set_entries(int index, std::string&& value) {
  entries_.Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:aafs.ReadDirResponse.entries)
}
inline void ReadDirResponse::set_entries(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  entries_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:aafs.ReadDirResponse.entries)
}
inline void ReadDirResponse::set_entries(int index, const char* value, size_t size) {
  entries_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:aafs.ReadDirResponse.entries)
}
inline std::string* ReadDirResponse::_internal_add_entries() {
  return entries_.Add();
}
inline void ReadDirResponse::add_entries(const std::string& value) {
  entries_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:aafs.ReadDirResponse.entries)
}
inline void ReadDirResponse::add_entries(std::string&& value) {
  entries_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:aafs.ReadDirResponse.entries)
}
inline void ReadDirResponse::add_entries(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  entries_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:aafs.ReadDirResponse.entries)
}
inline void ReadDirResponse::add_entries(const char* value, size_t size) {
  entries_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:aafs.ReadDirResponse.entries)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ReadDirResponse::entries() const {
  // @@protoc_insertion_point(field_list:aafs.ReadDirResponse.entries)
  return entries_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ReadDirResponse::mutable_entries() {
  // @@protoc_insertion_point(field_mutable_list:aafs.ReadDirResponse.entries)
  return &entries_;
}

// -------------------------------------------------------------------

// FileContent

// bytes data = 1;
inline void FileContent::clear_data() {
  data_.ClearToEmpty();
}
inline const std::string& FileContent::data() const {
  // @@protoc_insertion_point(field_get:aafs.FileContent.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileContent::set_data(ArgT0&& arg0, ArgT... args) {
 
 data_.SetBytes(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aafs.FileContent.data)
}
inline std::string* FileContent::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:aafs.FileContent.data)
  return _s;
}
inline const std::string& FileContent::_internal_data() const {
  return data_.Get();
}
inline void FileContent::_internal_set_data(const std::string& value) {
  
  data_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* FileContent::_internal_mutable_data() {
  
  return data_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* FileContent::release_data() {
  // @@protoc_insertion_point(field_release:aafs.FileContent.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
}
inline void FileContent::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (data_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:aafs.FileContent.data)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace aafs

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_hello_2eproto
